@extends('layouts.public')

@section('title', $service->name)

@section('content')
    <div class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><nav class="text-sm text-slate-500"><a href="{{ route('home') }}" class="hover:text-blue-600">Home</a><span class="mx-2">/</span><a href="{{ route('services.index') }}" class="hover:text-blue-600">Services</a><span class="mx-2">/</span><span class="text-slate-900">{{ $service->name }}</span></nav>
        <div class="mt-10 grid gap-10 lg:grid-cols-3"><div class="lg:col-span-2"><div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><x-dynamic-icon name="briefcase" class="h-7 w-7" /></div><p class="mt-6 font-semibold text-blue-600">{{ $service->category?->name ?? 'Consulting service' }}</p><h1 class="mt-2 text-4xl font-black text-slate-900">{{ $service->name }}</h1><div class="mt-5 flex flex-wrap gap-6 text-sm text-slate-600"><span><strong class="text-slate-900">TZS {{ number_format($service->price) }}</strong></span><span>{{ $service->processing_time ?? 'Processing time varies' }}</span></div><div class="prose prose-slate mt-10 max-w-none"><p>{{ $service->description }}</p></div>@if($service->requirements)<div class="mt-10"><h2 class="text-xl font-bold text-slate-900">Requirements</h2><p class="mt-3 whitespace-pre-line text-slate-600">{{ $service->requirements }}</p></div>@endif@if($service->documents?->count())<div class="mt-10"><h2 class="text-xl font-bold text-slate-900">Required documents</h2><ul class="mt-4 space-y-3">@foreach($service->documents as $document)<li class="flex items-center gap-3 text-slate-600"><x-dynamic-icon name="check-circle" class="h-5 w-5 text-emerald-500" />{{ $document->name ?? $document }}</li>@endforeach</ul></div>@endif</div>
            <aside class="h-fit lg:sticky lg:top-6"><div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-lg"><h2 class="text-xl font-bold text-slate-900">Apply Now</h2><p class="mt-2 text-sm text-slate-600">Share your details and we’ll get in touch.</p><form method="POST" action="{{ route('submissions.store') }}" enctype="multipart/form-data" class="mt-6 space-y-5">@csrf<input type="hidden" name="service_id" value="{{ $service->id }}"><div><label for="full_name" class="form-label">Full name</label><input id="full_name" name="full_name" value="{{ old('full_name') }}" required class="form-input" autocomplete="name">@error('full_name')<p class="form-error">{{ $message }}</p>@enderror</div><div><label for="email" class="form-label">Email address</label><input id="email" type="email" name="email" value="{{ old('email') }}" required class="form-input" autocomplete="email">@error('email')<p class="form-error">{{ $message }}</p>@enderror</div><div><label for="phone" class="form-label">Phone number</label><input id="phone" name="phone" value="{{ old('phone') }}" required class="form-input" autocomplete="tel">@error('phone')<p class="form-error">{{ $message }}</p>@enderror</div>@foreach($service->fields ?? [] as $field)<div><label for="field_{{ $field->id ?? $loop->index }}" class="form-label">{{ $field->label ?? $field['label'] ?? 'Additional information' }}@if($field->required ?? false)<span class="text-red-500"> *</span>@endif</label>@php($type = $field->type ?? $field['type'] ?? 'text')@if($type === 'textarea')<textarea id="field_{{ $field->id ?? $loop->index }}" name="fields[{{ $field->id ?? $loop->index }}]" rows="3" class="form-input">{{ old('fields.'.($field->id ?? $loop->index)) }}</textarea>@elseif($type === 'select')<select id="field_{{ $field->id ?? $loop->index }}" name="fields[{{ $field->id ?? $loop->index }}]" class="form-input"><option value="">Select an option</option>@foreach($field->options ?? $field['options'] ?? [] as $option)<option value="{{ $option }}" @selected(old('fields.'.($field->id ?? $loop->index)) === $option)>{{ $option }}</option>@endforeach</select>@else<input id="field_{{ $field->id ?? $loop->index }}" type="{{ $type }}" name="fields[{{ $field->id ?? $loop->index }}]" value="{{ old('fields.'.($field->id ?? $loop->index)) }}" class="form-input">@endif</div>@endforeach@if($service->documents?->count())<div><label class="form-label">Upload documents</label><input type="file" name="documents[]" multiple class="block w-full text-sm text-slate-500 file:mr-3 file:rounded-lg file:border-0 file:bg-blue-50 file:px-4 file:py-2 file:font-semibold file:text-blue-700"></div>@endif<button class="btn-primary w-full px-4 py-3 font-semibold" type="submit">Submit Application</button></form></div></aside></div>
    </div>
@endsection