@extends('layouts.admin')
@section('page_title','Operations dashboard')
@section('content')
<div class="admin-page-intro"><div><span class="admin-kicker">TODAY AT DIGITAL STAR</span><h2>Keep every request moving.</h2><p>Monitor workload, spot bottlenecks and jump straight into the work that needs attention.</p></div><div class="admin-date-card"><span>Today</span><strong>{{ now()->format('D, d M Y') }}</strong></div></div>
<div class="admin-kpi-grid">@foreach($kpis as $kpi)<a class="admin-kpi admin-kpi-{{ $kpi['tone'] }}" href="{{ $kpi['url'] }}"><span class="admin-kpi-label">{{ $kpi['label'] }}</span><strong>{{ number_format($kpi['value']) }}</strong><small>{{ $kpi['hint'] }}</small><span class="admin-kpi-arrow">↗</span></a>@endforeach</div>
<div class="admin-secondary-stats">@foreach($secondary as $item)<div><span>{{ $item['label'] }}</span><strong>{{ number_format($item['value']) }}</strong></div>@endforeach</div>
<div class="admin-dashboard-grid">
<section class="admin-panel admin-panel-large"><div class="admin-panel-head"><div><span class="admin-kicker">LIVE WORKLOAD</span><h3>Request status</h3></div><a href="{{ route('admin.submissions.index') }}">Open workspace →</a></div><div class="workload-list">@foreach($statusBreakdown as $row)<a class="workload-row" href="{{ route('admin.submissions.index',['status'=>$row['status']]) }}"><span class="workload-name"><i style="--status-color:{{ $row['color'] }}"></i>{{ $row['label'] }}</span><span class="workload-track"><b style="width:{{ $stats['total_submissions'] ? min(100,($row['count']/$stats['total_submissions'])*100) : 0 }}%;--status-color:{{ $row['color'] }}"></b></span><strong>{{ number_format($row['count']) }}</strong></a>@endforeach</div></section>
<section class="admin-panel"><div class="admin-panel-head"><div><span class="admin-kicker">QUICK ACTIONS</span><h3>Move work forward</h3></div></div><div class="admin-action-grid"><a class="admin-action primary" href="{{ route('admin.submissions.index') }}"><span class="action-icon">◫</span><div><strong>All requests</strong><small>Open the full queue</small></div><b>→</b></a><a class="admin-action" href="{{ route('admin.submissions.index',['status'=>\App\Models\Submission::STATUS_PENDING]) }}"><span class="action-icon amber">!</span><div><strong>Pending</strong><small>Waiting to start</small></div><b>→</b></a><a class="admin-action" href="{{ route('admin.submissions.index',['unassigned'=>1]) }}"><span class="action-icon blue">◎</span><div><strong>Unassigned</strong><small>Needs an owner</small></div><b>→</b></a><a class="admin-action" href="{{ route('admin.services.index') }}"><span class="action-icon green">✦</span><div><strong>Manage services</strong><small>Catalogue & fields</small></div><b>→</b></a></div></section></div>
<section class="admin-panel"><div class="admin-panel-head"><div><span class="admin-kicker">RECENT REQUESTS</span><h3>Latest applications</h3></div><div class="admin-panel-head-right"><span class="admin-inline-note"><b>{{ $stats['unassigned_submissions'] }}</b> unassigned</span><a href="{{ route('admin.submissions.index') }}">View all →</a></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Request</th><th>Customer</th><th>Service</th><th>Status</th><th>Owner</th><th>Received</th><th></th></tr></thead><tbody>@forelse($recent_submissions as $s)<tr><td><a class="admin-ref" href="{{ route('admin.submissions.show',$s) }}">{{ $s->reference_number }}</a></td><td><strong>{{ $s->customer_name }}</strong><small>{{ $s->customer_phone }}</small></td><td>{{ $s->service->name ?? '—' }}</td><td><span class="badge {{ $s->status_color }}">{{ $s->status_label }}</span></td><td>{{ $s->processedBy->name ?? 'Unassigned' }}</td><td>{{ $s->created_at?->format('d M · H:i') }}</td><td><a class="table-arrow" href="{{ route('admin.submissions.show',$s) }}">→</a></td></tr>@empty<tr><td colspan="7" class="admin-empty"><div class="admin-empty-icon">◫</div><strong>No applications yet</strong><span>New customer requests will appear here.</span></td></tr>@endforelse</tbody></table></div></section>
@endsection
