@extends('layouts.admin')
@section('page_title', $title)
@section('content')
<div class="report-detail-page">
<section class="admin-panel report-detail-hero"><div><span class="eyebrow">REPORTING</span><h2>{{ $title }}</h2><p>{{ $subtitle }}</p></div><div class="report-detail-actions"><a class="button button-outline" href="{{ route('admin.reports.index') }}">← Reports</a><a class="button button-dark" href="{{ route('admin.finance.index') }}">Finance →</a></div></section>
@if(in_array($type,['daily','weekly','monthly'],true))
<section class="report-kpi-grid"><article class="admin-panel"><span>Total requests</span><strong>{{ number_format((int)$data['total_submissions']) }}</strong><small>Created in this reporting period</small></article><article class="admin-panel"><span>Completed</span><strong>{{ number_format((int)$data['total_completed']) }}</strong><small>Marked completed in the period</small></article><article class="admin-panel"><span>Pending</span><strong>{{ number_format((int)$data['total_pending']) }}</strong><small>Still pending at report time</small></article><article class="admin-panel"><span>Completion rate</span><strong>{{ $data['total_submissions'] ? number_format(($data['total_completed']/$data['total_submissions'])*100,1) : '0.0' }}%</strong><small>Completed ÷ received</small></article></section>
@if($type==='daily')
<section class="admin-panel report-table-panel"><div class="panel-heading"><div><span class="eyebrow">DAY</span><h3>{{ $filters['date'] }}</h3></div></div><div class="report-simple-grid"><div><span>Received</span><strong>{{ $data['total_submissions'] }}</strong></div><div><span>Completed</span><strong>{{ $data['completed_today'] }}</strong></div><div><span>Rejected</span><strong>{{ $data['rejected'] }}</strong></div><div><span>In progress</span><strong>{{ $data['in_progress'] }}</strong></div></div></section>
@else
<section class="admin-panel report-table-panel"><div class="panel-heading"><div><span class="eyebrow">DAY BY DAY</span><h3>Activity breakdown</h3></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Requests</th><th>Completed</th><th>Pending</th><th>Completion</th></tr></thead><tbody>@forelse($data['daily_breakdown'] as $row)<tr><td><strong>{{ \Carbon\Carbon::parse($row->date)->format('D, d M Y') }}</strong></td><td>{{ $row->count }}</td><td>{{ $row->completed }}</td><td>{{ $row->pending }}</td><td>{{ $row->count ? number_format(($row->completed/$row->count)*100,1) : '0.0' }}%</td></tr>@empty<tr><td colspan="5">No submissions were recorded in this period.</td></tr>@endforelse</tbody></table></div></section>
@endif
@elseif($type==='staff')
<section class="admin-panel report-table-panel"><div class="panel-heading"><div><span class="eyebrow">STAFF WORKLOAD</span><h3>{{ count($data['staff']) }} team member(s)</h3></div></div><div class="table-wrap"><table><thead><tr><th>Staff member</th><th>Processed</th><th>Completed</th><th>Pending</th><th>Rejected</th><th>Completion</th></tr></thead><tbody>@forelse($data['staff'] as $staff)<tr><td><strong>{{ $staff['name'] }}</strong><small>{{ $staff['role_label'] }}</small></td><td>{{ $staff['total_processed'] }}</td><td>{{ $staff['completed'] }}</td><td>{{ $staff['pending'] }}</td><td>{{ $staff['rejected'] }}</td><td>{{ number_format($staff['completion_rate'],1) }}%</td></tr>@empty<tr><td colspan="6">No staff workload was recorded in this period.</td></tr>@endforelse</tbody></table></div></section>
@elseif($type==='services')
<section class="admin-panel report-table-panel"><div class="panel-heading"><div><span class="eyebrow">SERVICE DEMAND</span><h3>{{ count($data['services']) }} active service(s) with requests</h3></div></div><div class="table-wrap"><table><thead><tr><th>Service</th><th>Category</th><th>Requests</th><th>Completed</th><th>Pending</th><th>Completion</th></tr></thead><tbody>@forelse($data['services'] as $service)<tr><td><strong>{{ $service['name'] }}</strong></td><td>{{ $service['category_name'] ?: '—' }}</td><td>{{ $service['total'] }}</td><td>{{ $service['completed'] }}</td><td>{{ $service['pending'] }}</td><td>{{ number_format($service['completion_rate'],1) }}%</td></tr>@empty<tr><td colspan="6">No service requests were recorded in this period.</td></tr>@endforelse</tbody></table></div></section>
@endif
</div>
@endsection
