@extends('layouts.admin')
@section('page_title','Monthly report')
@section('content')
<div class="ds-report-page"><section class="admin-panel ds-report-hero"><div><span class="eyebrow">REPORTS / MONTHLY</span><h2>Monthly operations trend</h2><p>Review request volume and completion across a selected calendar month.</p></div><div class="ds-report-actions"><a class="button button-outline" href="{{ route('admin.reports.index') }}">← Reports</a><a class="button button-dark" href="{{ route('admin.reports.staff-performance') }}">Staff →</a></div></section>
<section class="admin-panel ds-report-filter"><form method="GET"><label>Month<select name="month">@for($m=1;$m<=12;$m++)<option value="{{ $m }}" @selected($filters['month']==$m)>{{ \Carbon\Carbon::create()->month($m)->format('F') }}</option>@endfor</select></label><label>Year<input type="number" min="2000" max="2100" name="year" value="{{ $filters['year'] }}"></label><button class="button button-yellow" type="submit">Apply month</button></form></section>
<section class="ds-kpi-grid"><article class="admin-panel ds-kpi"><span>Total requests</span><strong>{{ $data['total_submissions'] }}</strong><small>Created this month</small></article><article class="admin-panel ds-kpi"><span>Completed</span><strong>{{ $data['total_completed'] }}</strong><small>Completed during the month</small></article><article class="admin-panel ds-kpi"><span>Pending</span><strong>{{ $data['total_pending'] }}</strong><small>Pending at report time</small></article><article class="admin-panel ds-kpi"><span>Completion rate</span><strong>{{ $data['total_submissions'] ? number_format(($data['total_completed']/$data['total_submissions'])*100,1) : '0.0' }}%</strong><small>Completed ÷ received</small></article></section>
<section class="admin-panel ds-panel"><div class="panel-heading"><div><span class="eyebrow">CALENDAR VIEW</span><h3>{{ \Carbon\Carbon::create($data['year'],$data['month'],1)->format('F Y') }}</h3></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Requests</th><th>Completed</th><th>Pending</th><th>Completion</th></tr></thead><tbody>@forelse($data['daily_breakdown'] as $row)<tr><td><strong>{{ \Carbon\Carbon::parse($row->date)->format('D, d M Y') }}</strong></td><td>{{ $row->count }}</td><td>{{ $row->completed }}</td><td>{{ $row->pending }}</td><td>{{ $row->count ? number_format(($row->completed/$row->count)*100,1) : '0.0' }}%</td></tr>@empty<tr><td colspan="5">No requests were recorded in this month.</td></tr>@endforelse</tbody></table></div></section>
</div>
@push('styles')<style>.ds-report-page{display:grid;gap:18px}.ds-report-hero{display:flex;justify-content:space-between;gap:24px;align-items:flex-end}.ds-report-hero h2{margin:6px 0 8px}.ds-report-hero p{margin:0;color:#334155;max-width:720px;font-size:15px;line-height:1.65}.ds-report-actions{display:flex;gap:10px}.ds-report-filter form{display:flex;gap:12px;align-items:flex-end;flex-wrap:wrap}.ds-report-filter label{display:grid;gap:7px;font-weight:700;font-size:14px}.ds-report-filter input,.ds-report-filter select{min-width:190px}.ds-kpi-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.ds-kpi{display:grid;gap:8px}.ds-kpi span{font-size:14px;font-weight:700;color:#334155}.ds-kpi strong{font-size:30px;line-height:1}.ds-kpi small{color:#475569;font-size:13px}.ds-panel{padding:20px}@media(max-width:900px){.ds-report-hero{display:grid}.ds-kpi-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.ds-kpi-grid{grid-template-columns:1fr}.ds-report-actions .button{flex:1}}
</style>@endpush
@endsection