@extends('layouts.admin')
@section('page_title','Message from '.$message->name)
@section('content')
<div class="ds-message-view">
<section class="admin-panel ds-message-hero"><div><span class="eyebrow">MESSAGE {{ $message->id }}</span><h2>{{ $message->subject ?: 'General enquiry' }}</h2><p>Received {{ $message->created_at?->format('d M Y, H:i') }} · {{ $message->read_at ? 'Read' : 'Unread' }}</p></div><a class="button button-outline" href="{{ route('admin.contact-messages.index') }}">← Messages</a></section>
<section class="ds-message-layout">
<article class="admin-panel ds-message-content"><div class="ds-contact-meta"><div><span>Name</span><strong>{{ $message->name }}</strong></div><div><span>Email</span><a href="mailto:{{ $message->email }}">{{ $message->email }}</a></div><div><span>Phone</span>@if($message->phone)<a href="tel:{{ $message->phone }}">{{ $message->phone }}</a>@else<strong>Not provided</strong>@endif</div></div><div class="ds-message-body">{!! nl2br(e($message->message)) !!}</div></article>
<aside class="admin-panel ds-message-actions"><span class="eyebrow">NEXT ACTION</span><h3>Respond to the customer</h3><p>Use the contact details above to respond through the channel that fits the enquiry.</p><div class="ds-action-stack"><a class="button button-yellow" href="mailto:{{ $message->email }}?subject={{ rawurlencode('Re: '.($message->subject ?: 'Your enquiry to Digital Star Consultants')) }}">Reply by email →</a>@if($message->phone)<a class="button button-outline" href="tel:{{ $message->phone }}">Call {{ $message->name }}</a>@endif</div><div class="ds-danger-block"><span>Danger zone</span><form method="POST" action="{{ route('admin.contact-messages.destroy',$message) }}" onsubmit="return confirm('Delete this message?')">@csrf @method('DELETE')<button class="button button-danger" type="submit">Delete message</button></form></div></aside>
</section></div>
@push('styles')<style>
.ds-message-view{display:grid;gap:18px}.ds-message-hero{display:flex;justify-content:space-between;align-items:flex-end;gap:20px}.ds-message-hero h2{margin:6px 0 8px}.ds-message-hero p{margin:0;color:#475569;font-size:14px}.ds-message-layout{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(280px,.8fr);gap:18px}.ds-message-content,.ds-message-actions{padding:22px}.ds-contact-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding-bottom:18px;border-bottom:1px solid #e2e8f0}.ds-contact-meta div{display:grid;gap:5px}.ds-contact-meta span,.ds-danger-block>span{font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:#64748b}.ds-message-body{padding-top:22px;font-size:16px;line-height:1.8;color:#0f172a}.ds-message-actions{display:grid;align-content:start;gap:12px}.ds-message-actions h3{margin:0}.ds-message-actions p{margin:0;color:#475569;line-height:1.6}.ds-action-stack{display:grid;gap:10px}.ds-action-stack .button{justify-content:center}.ds-danger-block{margin-top:12px;padding-top:18px;border-top:1px solid #e2e8f0;display:grid;gap:10px}.ds-danger-block .button{width:100%}@media(max-width:900px){.ds-message-layout{grid-template-columns:1fr}.ds-contact-meta{grid-template-columns:1fr 1fr}}@media(max-width:560px){.ds-message-hero{display:grid}.ds-contact-meta{grid-template-columns:1fr}}
</style>@endpush
@endsection