extension_dir = "ext"
extension=openssl
extension=curl
extension=mbstring
extension=fileinfo
extension=zip
extension=pdo_sqlite
extension=sqlite3
date.timezone = Africa/Dar_es_Salaam
memory_limit = 512M
