@extends('layouts.public')

@section('title', 'Track Application')

@section('content')
    <section class="bg-slate-950 px-4 py-16 text-white sm:px-6 lg:px-8"><div class="mx-auto max-w-3xl text-center"><p class="font-semibold text-blue-300">Stay informed</p><h1 class="mt-3 text-4xl font-black">Track your application</h1><p class="mt-4 text-slate-300">Enter the reference number from your confirmation email.</p><form method="GET" action="{{ route('submissions.track') }}" class="mx-auto mt-8 flex max-w-xl gap-3"><input name="reference_number" value="{{ request('reference_number') }}" placeholder="e.g. DSC-123456" class="form-input flex-1" required><button class="btn-primary px-6 py-3 font-semibold">Track</button></form></div></section>
    <section class="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
        @if(isset($submission) && $submission)
            @php($statuses = ['submitted' => 'Submitted', 'under_review' => 'Under Review', 'processing' => 'Processing', 'completed' => 'Completed']) @php($current = array_search($submission->status, array_keys($statuses), true)) @if($current === false) @php($current = 0) @endif
            <div class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-sm text-slate-500">Reference number</p><h2 class="mt-1 text-2xl font-bold text-slate-900">{{ $submission->reference_number }}</h2></div><span class="rounded-full bg-blue-50 px-4 py-2 text-sm font-bold capitalize text-blue-700">{{ str_replace('_', ' ', $submission->status) }}</span></div>
                <div class="mt-10 grid grid-cols-4 gap-2">@foreach($statuses as $key => $label)<div><div class="flex items-center">@if($loop->index <= $current)<span class="flex h-8 w-8 items-center justify-center rounded-full bg-blue-600 text-xs font-bold text-white"><x-dynamic-icon name="check" class="h-4 w-4" /></span>@else<span class="flex h-8 w-8 items-center justify-center rounded-full bg-slate-100 text-xs font-bold text-slate-400">{{ $loop->iteration }}</span>@endif@if(!$loop->last)<span class="mx-2 h-1 flex-1 rounded {{ $loop->index < $current ? 'bg-blue-600' : 'bg-slate-100' }}"></span>@endif</div><p class="mt-2 text-xs font-medium text-slate-600">{{ $label }}</p></div>@endforeach</div>
                <div class="mt-10 grid gap-4 border-t border-slate-100 pt-6 sm:grid-cols-3"><div><p class="text-xs text-slate-500">Customer</p><p class="mt-1 font-semibold text-slate-900">{{ $submission->customer?->full_name }}</p></div><div><p class="text-xs text-slate-500">Service</p><p class="mt-1 font-semibold text-slate-900">{{ $submission->service?->name }}</p></div><div><p class="text-xs text-slate-500">Priority</p><p class="mt-1 font-semibold capitalize text-slate-900">{{ $submission->priority ?? 'Normal' }}</p></div></div>
            </div>
            @if($submission->updates?->count())<div class="mt-8"><h2 class="text-xl font-bold text-slate-900">Updates</h2><div class="mt-4 space-y-4">@foreach($submission->updates as $update)<div class="rounded-xl border border-slate-200 p-5"><div class="flex justify-between gap-4"><h3 class="font-semibold text-slate-900">{{ $update->title }}</h3><time class="text-xs text-slate-500">{{ $update->created_at?->format('d M Y') }}</time></div><p class="mt-2 text-sm text-slate-600">{{ $update->message }}</p></div>@endforeach</div></div>@endif
        @elseif(request()->filled('reference_number'))
            <div class="rounded-2xl border border-red-100 bg-red-50 p-8 text-center"><h2 class="text-xl font-bold text-red-900">Application Not Found</h2><p class="mt-2 text-sm text-red-700">Check your reference number and try again.</p></div>
        @endif
    </section>
@endsection