<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#063d2b">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'Digital Star Consultants')</title>
    <meta name="description" content="@yield('meta_description', 'Digital Star Consultants delivers enterprise technology, government, business, and creative services across Africa and beyond.')">
    <link rel="canonical" href="{{ url()->current() }}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="@yield('title', 'Digital Star Consultants')">
    <meta property="og:description" content="@yield('meta_description', 'Enterprise technology, consulting, government, and creative services.')">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet">
    @stack('head')
</head>
<body class="bg-mist-50 font-sans text-ink-900 antialiased">
    <a href="#main-content" class="skip-link">Skip to content</a>
    <header class="site-header sticky top-0 z-40 text-white" x-data="{ open: false, servicesOpen: false }" @keydown.escape.window="open = false; servicesOpen = false">
        <div class="border-b border-white/10"><div class="mx-auto flex max-w-7xl items-center justify-between px-5 py-2 text-[11px] sm:px-8"><p class="text-white/65"><span class="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-accent-400 align-middle"></span>Practical solutions for important work.</p><a href="{{ route('public.submissions.track.form') }}" class="font-bold text-accent-400 transition hover:text-white">Track a request <span aria-hidden="true">↗</span></a></div></div>
        <nav aria-label="Primary navigation"><div class="mx-auto flex min-h-[4.7rem] max-w-7xl items-center justify-between gap-6 px-5 sm:px-8">
            <a href="{{ route('home') }}" class="group flex shrink-0 items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-accent-400 text-ink-900 shadow-lg transition group-hover:-rotate-3"><svg class="h-5 w-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path d="{{ $starPath }}"/></svg></span><span class="leading-none"><strong class="block font-display text-[15px] font-bold">Digital Star</strong><small class="mt-1 block text-[9px] font-bold uppercase tracking-[.22em] text-brand-300">Consultants</small></span></a>
            <div class="hidden items-center gap-7 lg:flex"><a href="{{ route('home') }}" class="nav-link py-2 text-[13px] font-bold {{ request()->routeIs('home') ? 'is-active' : '' }}">Home</a><div class="relative" @mouseenter="servicesOpen = true" @mouseleave="servicesOpen = false"><button type="button" @click="servicesOpen = !servicesOpen" :aria-expanded="servicesOpen.toString()" class="nav-link flex items-center gap-1.5 py-2 text-[13px] font-bold" :class="servicesOpen && 'is-active'">Services <span class="text-xs transition" :class="servicesOpen && 'rotate-180'">⌄</span></button><div x-show="servicesOpen" x-cloak x-transition.opacity class="absolute left-1/2 top-full z-50 w-[min(42rem,calc(100vw-2rem))] -translate-x-1/2 pt-4"><div class="mega-panel rounded-2xl p-5"><div class="flex items-end justify-between gap-4 border-b border-white/10 pb-4"><div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-accent-400">Service catalogue</p><p class="mt-1 text-xs text-white/55">Find a capable team for the work ahead.</p></div><a href="{{ route('public.services.index') }}" class="text-xs font-bold text-brand-300 hover:text-white">View all ↗</a></div><div class="mt-4 grid gap-2 sm:grid-cols-2">@forelse(array_slice($services, 0, 6) as $group)<a href="{{ $group['items'][0][1] ?? route('public.services.index') }}" class="reveal-card rounded-xl border border-white/10 bg-white/[.04] p-4"><p class="text-sm font-bold text-white">{{ $group['title'] }}</p><p class="mt-1 text-[11px] leading-relaxed text-white/50">{{ $group['blurb'] }}</p></a>@empty<p class="text-sm text-white/50">Services are being prepared.</p>@endforelse</div></div></div></div>@foreach(array_slice($navLinks, 1) as [$label, $href])<a href="{{ $href }}" class="nav-link py-2 text-[13px] font-bold {{ request()->is(ltrim($href, '/')) ? 'is-active' : '' }}">{{ $label }}</a>@endforeach</div>
            <div class="hidden items-center gap-2 lg:flex">@auth<a href="{{ auth()->user()->isManagement() ? route('admin.dashboard') : route('staff.dashboard') }}" class="btn btn-ghost">Dashboard</a>@endauth<a href="{{ route('public.submissions.track.form') }}" class="btn btn-outline">Track request</a><a href="{{ route('public.services.index') }}" class="btn btn-gold">Start a request <span aria-hidden="true">↗</span></a></div>
            <button type="button" @click="open = !open" :aria-expanded="open.toString()" aria-controls="mobile-menu" class="grid h-10 w-10 place-items-center rounded-xl border border-white/15 bg-white/[.05] text-white lg:hidden"><span class="sr-only">Toggle navigation</span><span x-show="!open">☰</span><span x-show="open" x-cloak>&times;</span></button>
        </div><div id="mobile-menu" x-show="open" x-cloak x-transition class="border-t border-white/10 bg-ink-900 lg:hidden"><div class="mx-auto max-w-7xl space-y-1 px-5 py-5 sm:px-8"><a href="{{ route('home') }}" class="block rounded-xl px-3 py-3 text-sm font-bold text-white hover:bg-white/10">Home</a><a href="{{ route('public.services.index') }}" class="block rounded-xl px-3 py-3 text-sm font-bold text-white hover:bg-white/10">Services</a>@foreach(array_slice($navLinks, 1) as [$label, $href])<a href="{{ $href }}" class="block rounded-xl px-3 py-3 text-sm font-bold text-white hover:bg-white/10">{{ $label }}</a>@endforeach<div class="grid gap-2 border-t border-white/10 pt-4 sm:grid-cols-2"><a href="{{ route('public.services.index') }}" class="btn btn-gold">Start a request</a><a href="{{ route('public.submissions.track.form') }}" class="btn btn-outline">Track request</a></div></div></div></nav>
    </header>
    <main id="main-content">@yield('content')</main>
    <section class="bg-ink-950 px-5 py-16 text-white sm:px-8"><div class="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 rounded-3xl border border-white/10 bg-white/[.04] px-6 py-8 sm:px-10 lg:flex-row lg:items-center"><div><p class="text-[10px] font-bold uppercase tracking-[.2em] text-accent-400">Need a clear next step?</p><h2 class="mt-3 max-w-xl font-display text-3xl font-bold tracking-tight sm:text-4xl">Tell us what you are trying to accomplish.</h2><p class="mt-3 max-w-xl text-sm leading-6 text-white/55">We will help you find the right service and the simplest route forward.</p></div><div class="flex w-full shrink-0 flex-col gap-3 sm:w-auto sm:flex-row"><a href="{{ route('public.services.index') }}" class="btn btn-gold">Explore services ↗</a><a href="{{ route('contact') }}" class="btn btn-outline">Contact us</a></div></div></section>
    <footer class="bg-ink-950 pb-8 text-white"><div class="mx-auto grid max-w-7xl gap-10 border-t border-white/10 px-5 py-12 sm:px-8 md:grid-cols-[1.5fr_1fr_1fr]"><div><a href="{{ route('home') }}" class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-lg bg-accent-400 text-ink-900"><svg class="h-4 w-4" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path d="{{ $starPath }}"/></svg></span><span class="font-display font-bold">Digital Star Consultants</span></a><p class="mt-5 max-w-md text-sm leading-6 text-white/45">Enterprise technology, government, business, and creative services delivered with a clear process and accountable support.</p></div><div><h2 class="text-[10px] font-bold uppercase tracking-[.2em] text-white/35">Explore</h2><ul class="mt-4 space-y-3 text-sm text-white/55"><li><a href="{{ route('about') }}" class="hover:text-brand-300">About us</a></li><li><a href="{{ route('why-us') }}" class="hover:text-brand-300">Why us</a></li><li><a href="{{ route('faq') }}" class="hover:text-brand-300">FAQ</a></li><li><a href="{{ route('contact') }}" class="hover:text-brand-300">Contact</a></li></ul></div><div><h2 class="text-[10px] font-bold uppercase tracking-[.2em] text-white/35">Services</h2><ul class="mt-4 space-y-3 text-sm text-white/55"><li><a href="{{ route('public.services.index') }}" class="hover:text-brand-300">All services ↗</a></li><li><a href="{{ route('public.submissions.track.form') }}" class="hover:text-brand-300">Track a request ↗</a></li></ul></div></div><div class="mx-auto flex max-w-7xl flex-col gap-2 border-t border-white/10 px-5 pt-6 text-[11px] text-white/30 sm:flex-row sm:items-center sm:justify-between sm:px-8"><p>&copy; {{ date('Y') }} Digital Star Consultants. All rights reserved.</p><p>Built for clear, useful progress.</p></div></footer>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    @stack('scripts')
</body>
</html>
