@extends('layouts.admin')
@section('page_title','Categories')
@section('content')
<div class="admin-page-intro"><div><span class="admin-kicker">CATALOGUE ARCHITECTURE</span><h2>Keep the service hierarchy clear and easy to manage.</h2><p>Four public pillars, their service groups, and the services inside them.</p></div><button class="button button-yellow" type="button" data-category-create>+ Add category</button></div>

<div class="category-admin-grid">
@foreach($categories->whereNull('parent_id') as $parent)
    <section class="category-architecture-card" data-category-card="{{ $parent->id }}">
        <header><div class="category-icon">{{ $parent->icon ?: '✦' }}</div><div><span class="admin-kicker">PILLAR {{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $parent->name }}</h3><p>{{ $parent->description ?: 'No description added.' }}</p></div><span class="badge {{ $parent->is_active?'success':'secondary' }}">{{ $parent->is_active?'Active':'Hidden' }}</span></header>
        <div class="category-group-list">
        @foreach($categories->where('parent_id',$parent->id) as $child)
            <article class="category-group-row" data-child-id="{{ $child->id }}"><div class="category-group-icon">{{ $child->icon ?: '◇' }}</div><div class="category-group-copy"><strong>{{ $child->name }}</strong><span>{{ $child->services()->count() }} services · {{ $child->is_active?'Visible':'Hidden' }}</span></div><div class="category-row-actions"><button type="button" data-edit-category="{{ $child->id }}">Edit</button><a href="{{ route('admin.services.index',['category_id'=>$child->id]) }}">View services</a></div></article>
        @endforeach
        </div>
        <footer><span>{{ $parent->children_count }} service groups</span><button type="button" class="text-button" data-edit-category="{{ $parent->id }}">Edit pillar</button></footer>
    </section>
@endforeach
</div>

<div class="admin-modal" id="category-modal" aria-hidden="true">
<div class="admin-modal-backdrop" data-close-cat></div><div class="admin-modal-card" role="dialog" aria-modal="true"><div class="admin-modal-head"><div><span class="admin-kicker" id="category-kicker">NEW CATEGORY</span><h3 id="category-title">Add category</h3></div><button class="modal-close" type="button" data-close-cat>×</button></div>
<form id="category-form" class="admin-form-grid">@csrf<input type="hidden" id="category-id"><input type="hidden" name="_method" id="category-method" value="POST"><label class="span-2"><span>Name</span><input name="name" id="category-name" required placeholder="e.g. Passport & Immigration"></label><label class="span-2"><span>Parent pillar</span><select name="parent_id" id="category-parent"><option value="">Top-level pillar</option>@foreach($categories->whereNull('parent_id') as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></label><label class="span-2"><span>Description</span><textarea name="description" id="category-description" rows="4"></textarea></label><label><span>Icon</span><input name="icon" id="category-icon-input" placeholder="passport, briefcase..."></label><label><span>Color</span><input name="color" id="category-color" placeholder="#1E3A8A"></label><label><span>Sort order</span><input type="number" name="sort_order" id="category-sort" min="0" value="0"></label><label class="toggle-field"><span>Visibility</span><span class="check-row"><input type="checkbox" name="is_active" id="category-active" value="1" checked> Visible to customers</span></label><div class="admin-modal-foot span-2"><span class="modal-status" id="category-status"></span><div><button class="button button-outline" type="button" data-close-cat>Cancel</button><button class="button button-yellow" type="submit" id="category-submit">Create category</button></div></div></form></div></div>
<script>
(()=>{const m=document.getElementById('category-modal'),f=document.getElementById('category-form'),csrf=document.querySelector('meta[name="csrf-token"]').content;const id=document.getElementById('category-id'),method=document.getElementById('category-method'),name=document.getElementById('category-name'),parent=document.getElementById('category-parent'),desc=document.getElementById('category-description'),icon=document.getElementById('category-icon-input'),color=document.getElementById('category-color'),sort=document.getElementById('category-sort'),active=document.getElementById('category-active'),title=document.getElementById('category-title'),kicker=document.getElementById('category-kicker'),submit=document.getElementById('category-submit'),status=document.getElementById('category-status');const open=()=>{m.classList.add('is-open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')},close=()=>{m.classList.remove('is-open');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')};const reset=()=>{f.reset();id.value='';method.value='POST';sort.value='0';active.checked=true;title.textContent='Add category';kicker.textContent='NEW CATEGORY';submit.textContent='Create category';status.textContent=''};document.querySelector('[data-category-create]').addEventListener('click',()=>{reset();open()});document.querySelectorAll('[data-close-cat]').forEach(x=>x.addEventListener('click',close));document.querySelectorAll('[data-edit-category]').forEach(b=>b.addEventListener('click',async()=>{open();status.textContent='Loading…';kicker.textContent='EDIT CATEGORY';title.textContent='Edit category';try{const r=await fetch('{{ url('/admin/categories') }}/'+b.dataset.editCategory,{headers:{Accept:'application/json'}});const j=await r.json();const c=j.data;id.value=c.id;method.value='PUT';name.value=c.name||'';parent.value=c.parent_id||'';desc.value=c.description||'';icon.value=c.icon||'';color.value=c.color||'';sort.value=c.sort_order||0;active.checked=!!c.is_active;submit.textContent='Save changes';status.textContent=''}catch(e){status.textContent='Could not load category.'}}));f.addEventListener('submit',async e=>{e.preventDefault();status.textContent='Saving…';const cid=id.value;const url=cid?'{{ url('/admin/categories') }}/'+cid:'{{ route('admin.categories.store') }}';const fd=new FormData(f);fd.set('_method',cid?'PUT':'POST');try{const r=await fetch(url,{method:'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':csrf},body:fd});const j=await r.json();if(!r.ok)throw new Error(j.message||'Save failed');location.reload()}catch(err){status.textContent=err.message||'Could not save category.'}})})();
</script>
@endsection
